DROP DATABASE IF EXISTS foods;
CREATE DATABASE foods;
USE foods;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(225),
    email VARCHAR(225),
    password VARCHAR(225)
);

CREATE TABLE recipies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(225),
    image VARCHAR(225),
    ingredients VARCHAR(500),
    making_procedure VARCHAR(500),
    video VARCHAR(225)
);

INSERT INTO recipies (name, image, ingredients, making_procedure, video) VALUES
("burger", "static/images/burger.jpg", "Ground beef (500g), hamburger buns, lettuce, tomato, cheese slices, onions, pickles, ketchup, mustard, salt, pepper, oil", "Mix the ground beef with salt and pepper. Form into patties. Cook on medium heat for about 4-5 minutes per side. Add cheese on top of each patty during the last minute of cooking to melt. Toast the hamburger buns on the grill. Assemble the burger by placing the cooked patty on the bun, topped with lettuce, tomato slices, pickles, onions, ketchup, and mustard.", "https://youtu.be/c7Dwt4CHrwI?si=QbsYMXqI8a-m47RR"),
("butter_naan", "static/images/butter_naan.jpg", "All-purpose flour, baking powder, salt, sugar, butter, milk, yogurt.", "Mix the dry ingredients together. Gradually add milk and yogurt to form a soft dough. Let the dough rest for a few hours. Divide the dough into balls and roll each ball into a flat, oval shape. Cook on a hot griddle or skillet, applying butter to each side until it turns golden brown and puffs up.", "https://youtu.be/H3tW-UFSojU?si=k7zHlJralBjUJmn4"),
("chai", "static/images/chai.jpg", "Water, black tea leaves, milk, sugar, cardamom, cinnamon, cloves, ginger.", "Boil water with the spices for a few minutes to infuse the flavors. Add the tea leaves and simmer for a few minutes. Add milk and sugar to taste, bring to a boil, then simmer for a few more minutes. Strain into cups and serve hot.", "https://youtu.be/sC124g6CSn8?si=2gsI1EcoLXbXPwPp"),
("chapati", "static/images/chapati.jpg", "Whole wheat flour, water, salt, oil.", "Mix the flour, salt, and water to form a soft dough. Knead well and let it rest. Divide the dough into small balls. Roll each ball into a thin circle. Cook on a hot griddle until it puffs up, flipping to cook evenly on both sides.", "https://youtu.be/L0fRM0feSgM?si=MxJ0flhguDC3KnnZ"),
("chole_bhature", "static/images/chole_bhature.jpg", "For Chole: Chickpeas, onions, tomatoes, garlic, ginger, chole masala, salt, oil. For Bhature: All-purpose flour, yogurt, baking powder, salt, sugar, oil for frying.", "Soak chickpeas overnight, then cook until tender. Sauté onions, tomatoes, garlic, ginger, and spices in oil, then add to the chickpeas and simmer. For Bhature: Mix flour, yogurt, baking powder, salt, and sugar to form a dough. Let it rest, then divide and roll into circles. Deep fry until puffed and golden.", "https://youtu.be/M-ohmJswy6A?si=cx4XQqOXhzZZ4xwc"),
("dal_makhani", "static/images/dal_makhani.jpg", "Black lentils, red kidney beans, onions, tomatoes, garlic, ginger, cream, butter, spices.", "Soak lentils and beans overnight. Cook with water until tender. Sauté onions, tomatoes, garlic, ginger, and spices in butter. Add to lentils and beans. Simmer and finish with cream.", "https://youtu.be/FTIjbV6yczo?si=1jg6vvk-L1uu5jvQ"),
("dhokla", "static/images/dhokla.jpg", "Gram flour, yogurt, turmeric, baking soda, sugar, lemon juice, green chili, mustard seeds, coriander leaves, water.", "Mix gram flour with yogurt and water to make a batter. Add turmeric and let it ferment. Before steaming, add baking soda and pour into a greased pan. Steam until cooked. Temper with mustard seeds, green chili, and add coriander leaves on top.", "https://youtu.be/w_2eb9uaXns?si=k1NqDCFOJNWgeLLK"),
("fried_rice", "static/images/fried_rice.jpg", "Cooked rice, eggs, carrots, peas, onions, soy sauce, oil, green onions.", " Scramble the eggs in oil and set aside. In the same pan, sauté carrots, peas, and onions. Add rice and soy sauce, mixing well. Add the scrambled eggs back in and mix. Garnish with chopped green onions.", "https://youtu.be/Ku26SDMkyZc?si=lD6U__igQ0kGjLs_"),
("idli", "static/images/idli.jpg", "Parboiled rice, split black lentils (urad dal), salt, water.", "Soak the rice and lentils separately overnight. Grind each to a paste and mix together. Ferment overnight. Pour into idli molds and steam until set.", "https://youtu.be/9wmXpHn8KCs?si=pUp6YRH4werK9tqP"),
("jalebi", "static/images/jalebi.jpg", "All-purpose flour, yogurt, turmeric for color, baking soda, sugar, water, saffron, cardamom, oil for frying.", "Mix flour, yogurt, and water to make a batter. Let it ferment overnight. Add turmeric and baking soda. Pour into a squeeze bottle or piping bag. Fry in hot oil in spiral shapes. Make syrup with sugar, water, saffron, and cardamom. Dip the fried spirals into the syrup.", "https://youtu.be/hgwdaU-K5wk?si=yakNS5auL091Kjdb"),
("kaathi_rolls", "static/images/kaathi_rolls.jpg", "Wheat flour (for the rolls), boneless chicken or paneer (cubed), onions (sliced), green peppers (sliced), spices (garam masala, cumin, coriander powder), yogurt, green chutney, oil, salt.", "Prepare dough for the rolls and set aside. Marinate the chicken or paneer in spices and yogurt. Pan-fry until cooked. Roll out the dough into thin circles and cook on a hot tawa. Place the cooked filling, onions, peppers, and green chutney on the cooked bread, roll tightly, and serve.", "https://youtu.be/Wb95nUQZLXM?si=SQ4rvYMkNaIp5w-J"),
("kadai_paneer", "static/images/kadai_paneer.jpg", "Paneer (cubed), bell peppers (cubed), onions (cubed), tomatoes (pureed), garlic (minced), ginger (minced), kadai masala (coriander seeds, cumin seeds, dried red chilies), cream, oil, salt.", "Roast coriander seeds, cumin seeds, and dried red chilies. Grind into a powder (kadai masala). Heat oil, add garlic and ginger, then onions, and bell peppers. Add tomato puree, kadai masala, and salt. Cook until oil separates. Add paneer and cream. Cook for a few minutes and serve.", "https://youtu.be/to27J3mtgoA?si=2O7FYLJbBXfO9jGt"),
("kulfi", "static/images/kulfi.jpg", "Milk, sugar, cardamom, saffron, pistachios (chopped).", "Boil milk until it reduces to one-third of its original volume, stirring constantly. Add sugar, cardamom, and saffron. Allow to cool. Pour into molds, sprinkle chopped pistachios on top, and freeze until set.", "https://youtu.be/CrA31nCzyD8?si=jiqKejeEn9HJOcSG"),
("masala_dosa", "static/images/masala_dosa.jpg", "Dosa batter (rice and urad dal soaked, ground, and fermented), potatoes (boiled and mashed), onions (sliced), mustard seeds, turmeric, curry leaves, green chilies, salt, oil.", "Prepare dosa batter and ferment overnight. For the filling, heat oil, splutter mustard seeds, add onions, curry leaves, green chilies, turmeric, and salt. Add mashed potatoes and mix well. Cook dosas on a hot griddle, place some filling on one half, fold, and serve with chutney and sambar.", "https://youtu.be/J75VQSxOtdo?si=6az5TeshPHS7Wmg8"),
("momos", "static/images/momos.jpg", "All-purpose flour, ground chicken or vegetables, onion, garlic, ginger, soy sauce, oil, salt, water.", "Mix flour with water and a little oil to form a smooth dough. Mix finely chopped or ground filling with onion, garlic, ginger, soy sauce, and salt. Roll out small circles from the dough, place filling in the center, and pleat to seal. Steam the momos until cooked through.", "https://youtu.be/kfvXn1RMRpY?si=daixCgSUaH4kgF8P"),
("paani_puri", "static/images/paani_puri.jpg", "Semolina (for puris), tamarind, jaggery, mint leaves, coriander leaves, green chilies, boiled potatoes (mashed), chickpeas, chaat masala, black salt, water.", " Make a dough with semolina and water, roll out small circles, and deep fry until crisp. Blend tamarind, jaggery, mint, coriander, green chilies, chaat masala, and water to make the paani. Mix mashed potatoes with chickpeas, chaat masala, and salt for the filling. Break a small hole in the puri, fill with the potato mixture, dip in the paani, and eat immediately.", "https://youtu.be/Yb0eNau56UA?si=3ZQiMO8CYkr5qxLV"),
("pakode", "static/images/pakode.jpg", "Gram flour, water, spices (turmeric, chili powder, garam masala), vegetables (potato, onion, spinach, cauliflower), salt, oil for frying.", "Make a batter with gram flour, water, spices, and salt. Slice vegetables and dip in the batter. Deep fry in hot oil until golden brown. Serve with mint chutney or ketchup.", "https://youtu.be/vJ-x-2Klnhg?si=wldDCWZWKQ_5QI1u"),
("pav_bhaji", "static/images/pav_bhaji.jpg", "Pav (bread rolls), mixed vegetables (cauliflower, potatoes, peas, carrots), onions, tomatoes, ginger-garlic paste, pav bhaji masala, butter, lemon, coriander leaves, salt.", "Boil and mash the vegetables. Heat butter in a pan, sauté onions, add ginger-garlic paste, tomatoes, pav bhaji masala, and salt. Add mashed vegetables, water if needed, and cook until thick. Serve with buttered and toasted pav, diced onions, lemon wedges, and chopped coriander.", "https://youtu.be/sAnPUIvPc1I?si=QSOlHFNZgxg6fRcV"),
("pizza", "static/images/pizza.jpg", " Pizza dough, tomato sauce, mozzarella cheese, toppings of choice (pepperoni, mushrooms, bell peppers, onions), olive oil, oregano, basil.", "Stretch out the pizza dough on a baking tray. Spread tomato sauce over the base. Sprinkle mozzarella cheese and add toppings of choice. Drizzle with olive oil and sprinkle oregano and basil. Bake in a preheated oven at a high temperature until the crust is golden and cheese is bubbling.", "https://youtu.be/PK0czgdbHoY?si=U_1QPfGbjx4kgQIV");
